sudo: required
services:
 - docker
language: bash
script:
# prepare qemu
 - docker ino
 - docker run --rm --privileged multiarch/qemu-user-static:register --reset
 - docker pull hypriot/rpi-alpine-scratch
 - docker run -t --name rpi-mqtt hypriot/rpi-alpine-scratch sh -c 'apk update && apk add mosquitto-clients'
 - docker commit rpi-mqtt philipz/rpi-alpine-mqtt

# push image
 - >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker push philipz/rpi-alpine-mqtt
  fi
